### PR TITLE
Add asset check script + workflow

### PR DESCRIPTION
**Pull request by josh-hadley**
This PR adds a Python script + some related utilities and infrastructure to check that the project's asset folder, file, and metadata content are consistent with one another.

Note: the included workflow currently fails because the `Pregnant person` asset is missing the Medium-Dark/3D style folder (this is reported by the script and will show in the workflow run's output log).

### CODE REVIEW

**Comment by josh-hadley** [comment]
@microsoft-github-policy-service agree

**Comment by VladWinner** [comment]
> the included workflow currently fails because the Pregnant person asset is missing the Medium-Dark/3D style folder (this is reported by the script and will show in the workflow run's output log).

Related https://github.com/microsoft/fluentui-emoji/issues/21

**Review by williamch-ms — CHANGES_REQUESTED** [review]
Looks great @josh-hadley. One thing, can we remove the `2021_ranked.tsv` file and the `get_popular` method from the utils file?

**Comment by josh-hadley** [comment]
> can we remove the `2021_ranked.tsv` file and the `get_popular` method from the utils file?

Sure, done in https://github.com/microsoft/fluentui-emoji/pull/75/commits/6985267ce17258a3920b2b2ad5721878e70befe8

**Review by williamch-ms — APPROVED** [review]

**Pull request merged**
